version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: kibana:6.4.1
    ports:
      - "5601:5601"
